### PR TITLE
Update addon.xml.in

### PR DESCRIPTION
**Pull request by nexusle**
added german strings

### CODE REVIEW

**Comment by afedchin** [comment]
Please add german translation of strings.po
Then I'll merge this.

**Comment by nexusle** [comment]
Hi Anton,

how to create a folder called "German" in "Resources/Languages"? Can you do this? After this, I can create the german "strings.po"

Thanks

Am 23.08.2013 um 13:25 schrieb Anton Fedchin notifications@github.com:

**Comment by afedchin** [comment]
Add folder and add strings.po to it then add it to the repo then commit.

**Comment by afedchin** [comment]
@nexusle any news on this?

**Comment by nexusle** [comment]
Hi Anton,

I'm unable to create a folder "German" in xbmc-addon-iptvsimple / addons / pvr.iptvsimple / resources / language /

I only can make a new file in this path, but no folder. If there is an option to create folders, I couldn't find it.﻿

Am 12. September 2013 um 09:49 schrieb Anton Fedchin notifications@github.com:

**Comment by afedchin** [comment]
@nexusle, just create a file xbmc-addon-iptvsimple/addons/pvr.iptvsimple/resources/language/German/strings.po then add it to the repo. A folder will be added automatically.

**Comment by nexusle** [comment]
Done.

Am 12.09.2013 um 14:11 schrieb Anton Fedchin notifications@github.com:

**Pull request merged**
